# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

#  config.hostmanager.enabled = true
#  config.hostmanager.ignore_private_ip = false
#  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    # Puppetmaster on CentOS 7
    config.vm.provider "virtualbox" do |v|
      v.memory = 8192
    end
    puppet.vm.synced_folder ".", "/vagrant"
    puppet.vm.box = "centos/7"
    puppet.vm.hostname = "puppet.cavemanbeats"
    puppet.vm.network :public_network, ip: "192.168.1.66"
    puppet.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: '.git/'
    puppet.vm.synced_folder '../code', '/puppet_code', type: 'rsync'
    puppet.vm.synced_folder '../puppetserver', '/puppet_puppetserver', type: 'rsync'
  #  puppet.hostmanager.aliases = %w(puppet)
    puppet.vm.provision "shell", inline: <<-SHELL
      # sudo yum update -y
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum install puppetserver -y
      sudo rm -rf /etc/puppetlabs/code
      sudo ln -s /puppet_code /etc/puppetlabs/code
      sudo rm -rf /etc/puppetlabs/puppetserver
      sudo ln -s /puppet_puppetserver /etc/puppetlabs/puppetserver
      sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
      echo "*.cavemanbeats" | sudo tee /etc/puppetlabs/puppet/autosign.conf
      sudo /opt/puppetlabs/bin/puppetserver gem install hiera-eyaml
      sudo cp -r /vagrant/keys /etc/puppetlabs
      sudo chown puppet:puppet /etc/puppetlabs/keys/public_key.pkcs7.pem
      sudo chown puppet:puppet /etc/puppetlabs/keys/private_key.pkcs7.pem
      sudo service puppetserver start
    SHELL
  end

  config.vm.define "base" do |base|
    # base host on CentOS 7
    base.vm.box = "centos/7"
    base.vm.hostname = "base.cavemanbeats"
    base.vm.network :public_network, ip: "192.168.1.70"
    base.hostmanager.aliases = %w(base)
    base.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
      sudo yum install puppet-agent -y
      sudo service puppet start
    SHELL
  end

config.vm.define "webhost" do |webhost|
    # base host on CentOS 7
    webhost.vm.box = "centos/7"
    webhost.vm.hostname = "webhost.cavemanbeats"
    webhost.vm.network :public_network, ip: "192.168.1.150"
    webhost.hostmanager.aliases = %w(webhost)
    webhost.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
      sudo yum install puppet-agent -y
      sudo service puppet start
    SHELL
  end

  config.vm.define "monstack" do |monstack|
    # monitoring stack on CentOS 7
    monstack.vm.box = "centos/7"
    monstack.vm.hostname = "monstack.cavemanbeats"
    monstack.vm.network :public_network, ip: "192.168.1.60"
    monstack.hostmanager.aliases = %w(monstack)
    monstack.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
      sudo yum install puppet-agent -y
      sudo service puppet start
    SHELL
  end

  config.vm.define "nagios" do |nagios|
    # nagios host CentOS 7
    nagios.vm.box = "centos/7"
    nagios.vm.hostname = "nagios.cavemanbeats"
    nagios.vm.network :public_network, ip: "192.168.1.80", bridge: "en0: Ethernet"
    nagios.hostmanager.aliases = %w(nagios)
    nagios.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
      sudo yum install puppet-agent -y
      sudo service puppet start
    SHELL
  end

end
