# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  #  config.hostmanager.enabled = true
  #  config.hostmanager.ignore_private_ip = false
  #  config.hostmanager.include_offline = true
  
    config.vm.define "puppet" do |puppet|
      # Puppetmaster on CentOS 7
      config.vm.provider "virtualbox" do |v|
        v.memory = 8192
      end
      puppet.vm.synced_folder ".", "/vagrant"
      puppet.vm.box = "centos/7"
      puppet.vm.hostname = "puppet.example"
      puppet.vm.network :public_network, ip: "192.168.1.60"
      puppet.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: '.git/'
    #  puppet.hostmanager.aliases = %w(puppet)
      puppet.vm.provision "shell", inline: <<-SHELL
        sudo yum update -y
        sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
        sudo yum install puppetserver -y
        sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
        echo "*.example" | sudo tee /etc/puppetlabs/puppet/autosign.conf
        sudo /opt/puppetlabs/bin/puppetserver gem install hiera-eyaml
        sudo cp -r /vagrant/keys /etc/puppetlabs
        sudo chown puppet:puppet /etc/puppetlabs/keys/public_key.pkcs7.pem
        sudo chown puppet:puppet /etc/puppetlabs/keys/private_key.pkcs7.pem
        sudo service puppetserver start
      SHELL
    end
  
    config.vm.define "agent1" do |agent1|
      # base host on CentOS 7
      agent1.vm.box = "centos/7"
      agent1.vm.hostname = "agent1.example"
      agent1.vm.network :public_network, ip: "192.168.1.70"
      agent1.hostmanager.aliases = %w(agent1)
      agent1.vm.provision "shell", inline: <<-SHELL
        sudo yum update -y
        sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
        sudo yum install puppet-agent -y
        sudo service puppet start
      SHELL
    end
  
  config.vm.define "agent2" do |agent2|
      # base host on CentOS 7
      agent2.vm.box = "centos/7"
      agent2.vm.hostname = "agent2.example"
      agent2.vm.network :public_network, ip: "192.168.1.80"
      agent2.hostmanager.aliases = %w(agent2)
      agent2.vm.provision "shell", inline: <<-SHELL
        sudo yum update -y
        sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
        sudo yum install puppet-agent -y
        sudo service puppet start
      SHELL
    end  
  end
  
